name = "tweetdrop"
type = "javascript"
zone_id = ""
account_id = "bdb8fc9e053d4e6dee2f75abd28afc7e"
route = "tweetdrop.odyslam.com/*"
workers_dev = true

[build]
command = "yarn && yarn run build"
[build.upload]
format = "service-worker"

[env.production.vars]
TWITTER_BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAAOnOXQEAAAAAS0%2FC4qwzrXr6aOEmBjQDI%2FRw280%3D9hJkyuDRdJxFSrM3vrWuMs6yqbgpXFiFFQYBuA4ebCIMu9l7XK"
ETH_RPC_URL="ETH_RPC_URL=https://eth-mainnet.alchemyapi.io/v2/4Y_wlm-04oTrBmdqATgedTJcRqwLMEW6"
